In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import ast

In [2]:
import os
os.chdir(r'C:\Users\AnuragS\OneDrive\cv_project\Movie Recommendation System\data')
os.getcwd()

'C:\\Users\\AnuragS\\OneDrive\\cv_project\\Movie Recommendation System\\data'

In [3]:
df = pd.read_csv('cleaned_data_for_anylytics.csv')
df.head()

,id,title,tag
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [6]:
print(df.iloc[0]['tag'])

in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d samworthington zoesaldana sigourneyweaver jamescameron 2009

In [7]:
print(df.iloc[1]['tag'])

captain barbossa, long believed to be dead, has come back to life and is headed to the edge of the earth with will turner and elizabeth swann. but nothing is quite as it seems. adventure fantasy action captain barbossa, long believed to be dead, has come back to life and is headed to the edge of the earth with will turner and elizabeth swann. but nothing is quite as it seems. ocean drugabuse exoticisland eastindiatradingcompany loveofone'slife traitor shipwreck strongwoman ship alliance calypso afterlife fighter pirate swashbuckler aftercreditsstinger johnnydepp orlandobloom keiraknightley goreverbinski 2007

In [10]:
df.tag = df.tag.str.strip()

In [13]:
from sklearn.feature_extraction.text import CountVectorizer

In [14]:
cv = CountVectorizer(max_features=5000,stop_words='english')

In [16]:
vectors = cv.fit_transform(df['tag']).toarray()

In [ ]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], shape=(5000,))

In [23]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [24]:
def f_stem(text):
    stemmed = []
    for i in text.split():
        stemmed.append(ps.stem(i))

    str = ' '.join(stemmed)
    return str

In [25]:
str = 'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. action adventure fantasy sciencefiction in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d samworthington zoesaldana sigourneyweaver jamescameron 2009'

print(f_stem(str))

in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d samworthington zoesaldana sigourneyweav jamescameron 2009

In [26]:
df['tag_stemmed'] = df['tag'].apply(f_stem)

In [27]:
vectors2 = cv.fit_transform(df['tag_stemmed']).toarray()

In [28]:
vectors2

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(4799, 5000))

In [29]:
for i in cv.get_feature_names_out():
    print(i)

000
007
10
100
10th
11
12
13
14
15
150
16
17
17th
18
1890
18th
19
1910
1920
1930
1930s
1937
1940
1941
1944
1945
1950
1950s
1955
1959
1960
1960s
1962
1964
1965
1966
1967
1968
1969
1970
1970s
1971
1972
1973
1974
1975
1976
1977
1978
1979
1980
1980s
1981
1982
1983
1984
1985
1986
1987
1988
1989
1990
1991
1992
1993
1994
1995
1996
1997
1998
1999
19th
19thcenturi
20
200
2000
2001
2002
2003
2004
2005
2006
2007
2008
2009
2010
2011
2012
2013
2014
2015
2016
20th
21st
23
24
25
30
300
3d
40
50
500
60
60s
70
80
aaron
aaroneckhart
abandon
abbi
abduct
abil
abl
aboard
abov
abroad
absolut
abus
academ
academi
academy
accept
access
accid
accident
acclaim
accompani
accomplish
account
accus
ace
achiev
acquaint
acquir
act
action
activ
activist
activities
actor
actress
actual
ad
adam
adamsandl
adapt
add
addict
adjust
admir
admit
adolesc
adopt
ador
adrienbrodi
adrift
adult
adulteri
adulthood
adults
advanc
advantag
adventur
adventure
adventures
advertis
advic
advis
affair
affect
affluent
afghanistan
afraid
africa
african
aftercreditssting
afterlif
aftermath
ag
age
agediffer
agenc
agency
agenda
agent
agents
aggress
ago
agre
ahead
aid
ail
aim
air
airborn
aircraft
airplan
airport
aka
al
alabama
alan
alaska
albert
alcohol
alecbaldwin
alex
algeria
ali
alic
alice
alien
alieninvas
alienlife
aliens
alik
aliv
alive
alleg
allegedli
allen
alli
allianc
allies
allow
alon
alongsid
alpacino
alpha
alreadi
alter
altern
alway
alyssa
alzheimer
amanda
amateur
amaz
amazon
ambassador
ambit
ambiti
ambul
ambush
america
american
americanfootbal
ami
amid
amidst
amnesia
amp
amsterdam
amus
amy
amyadam
ana
anakin
analyst
ancient
anderson
andi
andrew
android
andy
angel
angela
angeles
angelinajoli
anger
angri
ani
anim
animalattack
animalhorror
animals
ann
anna
annafari
anne
annehathaway
annetteben
anni
annie
anniversari
announc
annual
anonym
anoth
answer
ant
antholog
anthoni
anthonyhopkin
anthropomorph
anti
antic
antihero
antiqu
antoniobandera
anyon
anyth
apart
apartheid
apartment
ape
apes
apocalyps
apocalypse
apocalypt
appar
appear
appl
apple
appli
appoint
appreci
apprehend
apprentic
approach
approaches
april
arab
arch
archaeologist
architect
arctic
area
aren
arena
argument
aris
aristocrat
arm
armi
armor
armsdeal
army
arnold
arnoldschwarzenegg
arrang
array
arrest
arriv
arrives
arrog
art
arthur
articl
artifact
artifici
artificialintellig
artist
artists
ash
ashley
ashleyjudd
ashtonkutch
asia
asian
asid
ask
aspect
aspir
assassin
assault
assembl
assign
assignment
assist
assistant
associ
assum
asteroid
astronaut
asylum
athlet
atlant
atom
atomicbomb
attack
attacks
attempt
attend
attent
attitud
attorney
attract
auction
audienc
audit
august
aunt
austin
australia
australian
author
auto
autobiograph
avail
aveng
averag
avoid
await
awak
awaken
awar
award
away
awesom
awkward
awri
awry
babe
babi
baby
bachelor
backdrop
background
backyard
bad
bag
bahama
bail
baker
balanc
ball
ballet
balloon
baltimor
ban
band
bandit
bangkok
banish
bank
banker
bankrobberi
bar
barbara
bare
bargain
barn
barney
baron
barri
barrier
barry
barrylevinson
bars
bas
base
basebal
basedoncomicbook
basedonnovel
basedonplay
basedonstagemus
basedontrueev
basedontruestori
basedontvseri
basedonvideogam
basedonyoungadultnovel
basement
basketbal
basketball
batman
battalion
battl
battle
battlefield
bay
beach
beam
bear
beard
beast
beat
beauti
beautiful
beauty
becam
becaus
becki
becom
becominganadult
bed
bedroom
bee
beer
befor
befriend
beg
began
begin
begins
behavior
belief
believ
bell
bella
belong
belov
ben
benaffleck
bend
beneath
benefit
benjamin
benkingsley
bennett
benstil
bent
berlin
best
bestfriend
bet
beth
betray
betrayal
better
betti
beverli
bibl
biblic
bid
big
bigger
biggest
bike
biker
bikini
bilbo
billi
billion
billionair
billmurray
billpaxton
billybobthornton
bind
biograph
biographi
biolog
biopic
bird
birth
birthday
bisexu
bishop
bit
bite
bitter
bizarr
black
blackmail
blackpeopl
blade
blame
blaze
blend
bless
blind
bliss
block
blond
blood
bloodi
bloodsplatt
bloodthirsti
bloom
blossom
blow
blu
blue
blunt
board
boat
bob
bobbi
bobbyfarrelli
bodi
body
bodyguard
bohemian
bold
bollywood
bomb
bond
bone
book
border
bore
boredom
boring
born
borrow
boss
boston
botch
bound
boundari
bounti
bountyhunt
bout
box
boxer
boy
boyd
boyfriend
boys
brad
bradleycoop
bradpitt
brain
brand
brandon
brave
braveri
brazil
brazilian
break
breakdown
breakup
breast
breath
breed
brendanfras
brent
brettratn
brew
brian
briandepalma
brick
bride
bridesmaid
bridg
brief
brien
bright
brilliant
bring
brink
britain
british
britishsecretservic
broadcast
broadway
broke
broken
broker
bronx
brook
brooklyn
brothel
brother
brotherbrotherrelationship
brothers
brothersisterrelationship
brought
brown
bruce
brucewilli
brutal
bu
buck
bud
buddi
buddy
budget
build
building
built
bullet
bulli
bumbl
bunch
bunker
bunni
burglar
buri
burn
bush
busi
business
businessman
bust
butch
butcher
butler
butt
button
buy
buzz
cabin
cabl
caesar
cage
cain
cairo
cal
caleb
california
calm
calvin
came
camera
cameraman
cameron
camerondiaz
camp
campaign
campbel
campbell
campu
canada
canadian
cancer
candi
candid
canin
cannib
capabl
caper
capit
capt
captain
captiv
captur
capture
car
caraccid
carchas
carcrash
card
care
career
carefre
caretak
cargo
caribbean
carl
carlo
carmen
carol
carolina
carrac
carri
carrie
cartel
carter
cartoon
case
casey
cash
casino
cast
castl
castle
casual
cat
cataclysm
catastroph
catch
cateblanchett
catherin
catherinekeen
catherinezeta
cathol
catholic
cattl
caught
caus
cause
cavalri
cave
celebr
celebration
cell
cellphon
cemeteri
center
centr
central
centuri
centuries
century
ceo
certain
chad
chain
chainsaw
challeng
chamber
champion
championship
chanc
chance
chang
change
changed
changes
channel
channingtatum
chao
chaos
chaotic
chapter
charact
character
characters
charg
charismat
charl
charli
charlie
charlizetheron
charlott
charm
chart
chase
chauffeur
cheat
check
cheerlead
chef
chemic
cher
chicago
chicken
chief
child
childabus
childhood
children
chill
china
chines
chip
chipmunk
chloe
chocol
choic
choice
chon
choos
chosen
chri
chriscolumbu
chrisevan
chrispin
chrisrock
christ
christian
christianbal
christin
christma
christmas
christmasparti
christoph
christopherplumm
christopherwalken
chronicl
chuck
church
cia
cindi
cinema
circl
circle
circu
circuit
circumst
circumstances
citi
citizen
city
civil
civilian
civilization
civilwar
claim
clair
clan
clark
clash
class
classic
classmat
classroom
clay
clean
clear
clerk
clever
client
clients
cliff
climat
climb
climber
clinteastwood
cliveowen
clock
clone
close
closer
cloud
clown
club
clue
clueless
clutch
coach
coast
coastal
cocain
cocki
code
codi
coffin
cohen
col
cold
coldwar
cole
colin
colinfarrel
colinfirth
collaps
collapse
colleagu
colleague
collect
collector
colleg
college
collid
collide
collis
colon
colonel
coloni
color
colorado
coma
combat
combin
come
comeback
comed
comedi
comedian
comedy
comet
comfort
comic
coming
comingofag
comingout
command
commando
commerci
commiss
commit
common
commun
communist
community
compani
companion
company
compet
competit
competition
complet
complex
complic
compos
compound
compromis
compton
compuls
comput
computer
conan
concern
concert
concoct
condit
condition
conduct
confeder
confess
confid
confin
conflict
confront
confus
congress
conman
connect
connecticut
conni
connor
conquer
conquest
conrad
consequ
consequences
conserv
consid
conspir
conspiraci
conspiracy
constant
constantli
construct
consum
contact
contain
contemporari
contend
content
contest
contin
continu
contract
contractor
control
controversi
convent
converg
convers
convict
convinc
cook
cool
cooper
cop
cope
cops
core
corleon
corner
corp
corpor
corporation
corps
corrupt
cost
costum
couldn
counselor
count
countess
countless
countri
country
countrysid
countryside
county
coup
coupl
couple
couples
courag
courage
cours
court
courtcas
courtroom
cousin
cover
covert
covet
cow
cowardli
cowboy
coyot
crab
crack
craft
craig
crane
crash
crate
crave
craze
crazi
creat
creation
creativ
creator
creatur
creature
creatures
credit
creepi
crew
cri
crime
crimefight
crimes
crimin
criminal
criminals
crisi
crisis
critic
crocodil
crook
crop
cross
crowd
crown
crucifixion
cruel
cruelti
cruis
cruise
crumbl
crusad
crush
crystal
cuba
cubagoodingjr
cube
culmin
cult
cultfilm
cultur
culture
cultureclash
cun
cup
cure
curiou
current
curs
curse
cusp
custodi
custody
custom
cut
cutthroat
cyberpunk
cyborg
cynic
dad
daili
dale
damag
damon
dan
danaykroyd
danc
dance
dancer
danger
daniel
danielcraig
danish
danni
danny
dannydevito
dannyglov
dare
dark
darkcomedi
darkest
darkness
dash
date
dates
daughter
daughters
dave
davi
david
dawn
day
daydream
days
dc
dccomic
dea
dead
deadli
deadliest
deaf
deal
dealer
dean
death
deathofafriend
deathpenalti
debt
debut
decad
decades
deceas
deceit
decept
decid
decis
declar
declin
dedic
deed
deep
deeper
deepli
defeat
defend
defens
defi
defin
deform
deke
delight
deliv
deliveri
delus
demand
demimoor
demon
demons
deni
denni
dennisquaid
dent
dentist
denzelwashington
depart
department
depend
depict
deposit
depress
depression
depth
deputi
derang
derek
descend
describ
desert
design
desir
desk
desol
despair
desper
despit
destin
destini
destiny
destroy
destroyed
destruct
destruction
detect
detective
detent
determin
detroit
deuc
devast
develop
devic
devil
devilish
deviou
devis
devot
devour
diabol
diagnos
dialogu
diamond
dian
diana
diane
dianekeaton
dianelan
diari
dick
dictat
did
didn
die
died
diego
dies
differ
different
difficult
difficulti
dig
dil
dilemma
diner
dinner
dinosaur
diplomat
dire
direct
director
dirt
dirti
dirtycop
disabl
disappear
disappeared
disappears
disast
disaster
disastr
discov
discoveri
discovery
discuss
diseas
disease
disfigur
disgrac
disguis
disillus
disney
disord
dispatch
disput
disrupt
distanc
distant
distract
distress
district
distrust
disturb
ditch
diva
dive
diver
divers
divid
divis
divorc
divorce
dj
dna
doc
doctor
document
documentari
documentary
dodg
doe
doesn
dog
doll
dollar
dolphin
domest
domin
domination
don
donaldsutherland
doncheadl
donnel
doom
door
doorstep
dorothi
doubl
double
doublelif
doubt
doug
dougla
dr
dracula
drag
dragon
drama
dramat
drastic
draw
drawn
dre
dread
dream
dreams
dress
drew
drewbarrymor
drift
drifter
drink
drinking
drive
driven
driver
drone
drop
drown
drug
drugabus
drugaddict
drugdeal
drugs
drugtraff
drunk
drunken
du
dualident
dub
duck
dude
duel
duke
dump
duncan
dunn
duo
dure
duringcreditssting
dust
dustinhoffman
dutch
duti
dwaynejohnson
dyinganddeath
dylan
dynam
dynasti
dysfunct
dysfunctionalfamili
dystopia
dystopicfutur
eager
earl
earli
earlier
earn
earth
earthquak
easi
easili
east
eastern
easy
eat
eccentr
econom
economi
ed
eddi
eddiemurphi
edg
edgar
edharri
editor
educ
education
edward
edwardburn
edwardnorton
eeri
effect
effort
egg
ego
egypt
egyptian
el
elabor
elderli
elect
electr
element
elena
elev
elijahwood
elimin
elit
elite
elizabeth
elizabethbank
ell
ella
elli
elliot
elliott
elm
elmo
els
elsa
elud
elus
elv
elvi
em
embark
embarrass
embassi
embroil
emerg
emigr
emilehirsch
emili
emily
emilyblunt
emma
emmaston
emot
emperor
empir
empire
employ
employe
employer
enabl
enchant
encount
encourag
end
endless
endur
enemi
enemies
enemy
energi
enforc
engag
engin
england
english
englishman
enigmat
enjoy
enlist
enorm
enrol
ensemblecast
enslav
ensu
ensues
ensur
entangl
enter
enterpris
entertain
enthusiast
entir
entiti
entrepreneur
environ
environment
epic
epidem
episod
equal
equip
er
era
eras
eric
erin
ernest
erot
erotic
erupt
escap
escape
escort
especi
espionag
establish
estat
esteem
esther
estrang
etern
ethan
ethanhawk
ethic
europ
european
eva
evad
evamend
eve
evening
event
events
eventu
eventually
everi
everybodi
everyday
everyon
everyth
evid
evil
evolut
evolv
ewanmcgregor
ex
exact
exactli
exam
examin
exchang
excit
exclus
execut
exercis
exhibit
exil
exist
existence
existenti
exorc
exot
exoticisland
expect
expectations
expected
expedit
expens
experi
experienc
experience
experiment
expert
explain
explod
exploit
explor
explos
expos
extend
extra
extramaritalaffair
extraordinari
extraterrestri
extraterrestrialtechnolog
extrem
extremeviol
eye
eyes
fabl
fac
face
facil
facility
fact
faction
factori
fade
fail
fails
fairi
fairytal
faith
fake
falcon
fall
fallen
fallinginlov
falls
fals
falseident
fame
famili
families
family
familyrelationship
famou
famous
fan
fangvamp
fans
fantasi
fantast
fantasyworld
far
farm
farmer
farmhouse
fascin
fashion
fast
faster
fastest
fat
fatal
fate
father
fatherdaughterrelationship
fathersonrelationship
favor
favorit
fbi
fbiagent
fear
fearless
fears
fearsom
featur
fed
feder
feed
feel
feet
feisti
fell
fellow
femal
female
femalefriendship
femalenud
femaleprotagonist
fend
feroci
festiv
festival
feud
fi
fiance
fiancé
fiancée
fiction
field
fierc
fifth
fight
fighter
figur
fil
file
film
filmmak
films
final
finale
financ
financi
finch
fine
finish
finn
fiona
firm
fish
fisherman
fistfight
fit
fix
flag
flame
flash
flashback
flat
fledgl
flee
fleet
flesh
fli
flight
fling
flint
flirt
flood
floor
florida
flower
flynn
focu
focus
foe
foil
foley
folk
follow
food
foot
footag
footbal
footchas
forbidden
forbiddenlov
forc
force
forces
ford
foreign
forest
forestwhitak
forev
forever
forg
forget
forgiv
form
formid
formula
fort
fortun
fortune
forward
foster
fought
foul
foundfootag
fourteen
fourth
fox
fragil
frame
franc
france
franchise
franci
francisco
francisfordcoppola
frank
frankenstein
franki
frankie
frantic
fratern
fraud
freak
fred
freddi
freddieprinzejr
free
freed
freedom
freeman
freez
french
frequent
fresh
freshman
friend
friendli
friends
friendship
frighten
frog
frontier
frozen
frustrat
fu
fuel
fugit
fulfil
fulli
fun
fund
funer
funeral
funni
furiou
futur
future
futurist
ga
gabriel
gabrielbyrn
gadget
gain
galact
galaxi
galaxy
gale
gambl
gambler
game
games
gandhi
gang
gangs
gangster
garag
garden
garfield
gari
garyoldman
gate
gather
gave
gay
gene
genehackman
gener
general
generation
genet
geniu
genius
gentl
genuin
geoffreyrush
georg
george
georgeclooney
georgia
gerardbutl
german
germani
germans
germany
getaway
ghetto
ghost
ghostli
giant
gift
gig
gigolo
gilbert
girl
girlfriend
girlfriends
girls
given
glamor
glass
glenn
glimps
global
globe
glori
glory
goal
god
goe
gold
golden
golf
gone
good
goodvsevil
goon
gordon
gore
gorgeou
gorilla
gossip
got
gotham
gotten
govern
government
governor
grace
grad
grade
gradual
graduat
graham
grand
grandfath
grandfather
grandmoth
grandmother
grant
graphic
grasp
grave
great
greater
greatest
greec
greed
greedi
greek
green
greg
gregkinnear
grew
grief
griev
griffin
grim
grip
grisli
gritti
ground
group
groupoffriend
grow
grown
gruesom
gu
guard
guardian
guerrilla
guest
guid
guidanc
guilt
guitar
gulf
gun
gunfight
gunman
gunsling
guru
guy
guypearc
guys
gwynethpaltrow
gym
gypsi
ha
hack
hacker
hair
half
halfway
hall
halleberri
halloween
hallucin
han
hand
handl
hands
handsom
hang
hannah
hansel
hapless
happen
happens
happi
happili
happiness
happy
hara
harass
harbor
hard
harden
harder
harlem
harm
harmoni
harold
harri
harriet
harrison
harrisonford
harrow
harry
harsh
hart
harvard
harvey
harveykeitel
hasn
hatch
hate
hatr
haunt
hauntedhous
haven
havoc
hawaii
haydenchristensen
haze
head
headlin
headquarters
heal
health
hear
heard
heart
heartbreak
heat
heather
heathledg
heaven
heavi
heavili
heavyweight
height
heir
heiress
heist
held
helen
helenmirren
helicopt
hell
help
henchmen
henri
hero
heroes
heroic
heroin
heroism
hi
hidden
hide
high
higher
highest
highland
highli
highschool
highway
hijack
hike
hilari
hill
hills
himalaya
hip
hire
histor
histori
historicalfigur
history
hit
hitch
hitchhik
hitler
hitman
ho
hockey
hoffman
hold
holden
hole
holi
holiday
holli
hollywood
home
homeinvas
homeland
homeless
hometown
homicid
homosexu
honest
honey
honeymoon
hong
honor
hood
hoodlum
hook
hop
hope
hopelessli
hopper
hord
horribl
horrif
horrifi
horror
hors
hospit
hospital
host
hostag
hostage
hostil
hot
hotel
hotelroom
hotshot
hottest
hound
hour
hous
house
household
housewif
howard
howev
hud
hudson
huge
hugh
hughgrant
hughjackman
hugo
human
humanity
humankind
humans
humili
humor
hundr
hunger
hungri
hunt
hunted
hunter
hunters
hurrican
hurt
hurtl
husband
hustler
hypnosi
hypnot
hyster
hyun
ianmckellen
ice
icecub
icon
idea
ideal
idealist
ident
identity
idol
idyl
ignit
ignor
ii
iii
il
ill
illeg
illegalimmigr
illegalprostitut
illicit
illness
illus
illustr
imag
imagin
imaginari
imagined
imax
immedi
immens
immigr
immort
impact
impend
imperi
imperson
implic
import
impos
imposs
impress
imprison
improv
inadvert
incest
incid
includ
incompet
increas
increasingli
incred
independ
independence
independentfilm
indi
india
indian
indiana
indianlead
individu
industri
industry
inept
inevit
inexplic
infam
infant
infatu
infect
infidel
infiltr
influenc
influenti
inform
inhabit
inherit
initi
inject
injur
injuri
inmat
inner
innoc
innocence
insan
insecur
insid
insight
insist
inspector
inspir
instal
instant
instantli
instead
instinct
institut
institution
instructor
insur
insurg
intellig
intend
intens
intent
interact
interfer
intergalact
intern
internet
interpret
interrog
intersect
intertwin
interview
intim
intoler
intrepid
intric
intrigu
introduc
invad
invaders
invas
invent
inventor
invest
investig
investigate
invis
invit
involv
iowa
ira
iran
iranian
iraq
iraqi
ireland
irish
iron
irresist
ishmael
islam
island
isn
isol
isra
israel
issu
itali
italian
italy
jack
jackass
jackblack
jacki
jackiechan
jacknicholson
jackson
jacob
jacqu
jade
jail
jake
jakegyllenha
jamal
jame
james
jamescaan
jamesfranco
jamesmarsden
jamesmcavoy
jami
jamie
jamiefoxx
jan
jane
japan
japanes
jason
jasonbateman
jasonle
jasonsegel
jasonstatham
javierbardem
jay
jazz
jealou
jealous
jealousi
jean
jeann
jedi
jeff
jeffbridg
jeffdaniel
jefferson
jeffrey
jenna
jenni
jennif
jenniferaniston
jenniferconnelli
jennifergarn
jenniferjasonleigh
jenniferlawr
jenniferlopez
jeopard
jerri
jersey
jerusalem
jess
jesseeisenberg
jessica
jessicaalba
jesu
jesus
jet
jew
jewel
jewish
jigsaw
jill
jim
jimbroadb
jimcarrey
jimmi
jimmy
jin
joan
joancusack
joaquinphoenix
job
jobs
jock
jodi
jodiefost
joe
joel
joelcoen
joelschumach
joey
john
johnc
johncusack
johngoodman
johnhurt
johnleguizamo
johnmalkovich
johnni
johnny
johnnydepp
johnson
johntravolta
johnturturro
join
jon
jonahhil
jonathan
jone
jones
jonvoight
jordan
joseph
josephgordon
josh
joshbrolin
joshhartnett
joshhutcherson
journal
journalist
journey
joy
jr
juan
judelaw
judg
juli
julia
julian
juliannemoor
juliarobert
julie
juliu
jump
june
jungl
jungle
junior
junki
juri
just
justic
justice
justin
justinlong
justintimberlak
kansa
kapoor
karat
karen
kari
kat
kate
katebeckinsal
katebosworth
katehudson
katewinslet
katherin
kathi
kati
katniss
kay
keanureev
keiraknightley
kelli
kelly
ken
kennethbranagh
kept
kermit
kevin
kevinbacon
kevincostn
kevinklin
kevinsmith
kevinspacey
key
kgb
khan
kick
kid
kidnap
kidnapp
kidnapped
kids
kidsandfamili
kiefersutherland
kill
killed
killer
killers
killing
kim
kind
kindli
king
kingdom
kingpin
kirk
kirstendunst
kiss
kit
kitchen
knew
knife
knight
knit
knock
know
knowledg
known
kong
korea
korean
kowalski
kristenstewart
kristenwiig
krueger
kumar
kung
kungfu
kurt
kurtrussel
kyle
la
lab
label
labor
laboratori
lac
lack
ladder
ladi
ladies
lady
ladykil
laid
lake
land
landscap
landscape
lane
languag
lapd
lara
larg
larger
largest
larri
laser
lasvega
late
later
latest
latin
laugh
launch
laura
lauralinney
laurencefishburn
lavish
law
lawman
lawrenc
laws
lawyer
lax
lay
lazi
le
lead
leader
leadership
leagu
learn
leav
lecter
led
lee
left
leg
legaci
legacy
legal
legend
legendari
legends
legion
lena
length
leo
leon
leonard
leonardodicaprio
lesbian
lesliemann
lesson
let
lethal
letter
level
levitt
lewi
lgbt
li
liaison
liamneeson
liar
liber
lie
lieuten
lif
life
lifelong
lifestyl
lifestyle
lifetim
lifetime
lift
light
lightn
lik
like
lili
limit
lincoln
linda
line
lines
link
lion
lisa
list
listen
liter
literari
literatur
littl
little
live
lives
living
liz
lizzi
ll
lloyd
lo
loan
local
locat
lock
logan
lola
london
londonengland
lone
loneli
loner
long
longer
longtim
look
loop
loos
loose
loot
lord
losangel
lose
loser
loss
lossofbroth
lossoffamili
lossoffath
lossoflov
lossofmoth
lost
lot
lotteri
lou
loui
louisiana
loung
lov
lovabl
love
loveatfirstsight
loveless
loveofone

In [30]:
df.head()

,id,title,tag,tag_stemmed
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di...","in the 22nd century, a parapleg marin is dispa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha...","captain barbossa, long believ to be dead, ha c..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...,a cryptic messag from bond’ past send him on a...
3,49026,The Dark Knight Rises,following the death of district attorney harve...,follow the death of district attorney harvey d...
4,49529,John Carter,"john carter is a war-weary, former military ca...","john carter is a war-weary, former militari ca..."

In [31]:
from sklearn.metrics.pairwise import cosine_similarity

In [35]:
similarity = cosine_similarity(vectors2)

In [37]:
similarity[0].shape

(4799,)

In [ ]:
sorted(list(enumerate(similarity[1])),reverse=True,key= lambda x:x[1])[1:6]

[(12, np.float64(0.2070196678027062)),
 (1673, np.float64(0.19112739302699858)),
 (962, np.float64(0.18670401120373462)),
 (57, np.float64(0.17407765595569782)),
 (109, np.float64(0.17320508075688773))]

In [52]:
def f_recomm(movie):
    """
    This function helps to get top 5 similar movies
    """
    _movie_index = df[df['title'] == movie].index[0]
    _distance = similarity[_movie_index]
    _ml = sorted(list(enumerate(_distance)),reverse=True,key= lambda x:x[1])[1:6]

    for mv in _ml:
        # print(mv[0])
        print(df.iloc[mv[0]].title)

In [43]:
df[df['title'] == 'Batman Begins'].index[0]

119

In [54]:
f_recomm('Avatar')

Aliens vs Predator: Requiem
Apollo 18
Meet Dave
Independence Day
Tears of the Sun